services:
  catalogdb:
    image: mongo
  basketdb : 
    image : redis:alpine
  discountdb :
      image: postgres
  pgadmin :
    image: dpage/pgadmin4
  orderDb :
    image: mcr.microsoft.com/mssql/server:2019-latest
  rabbitmq :
    image: rabbitmq:3-management-alpine



  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Catalog.Api/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: src/Basket.Api/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: src/Discount.api/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: src/Discount.gRPC/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: src/Ordering.Api/Dockerfile

  ocelotapigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: src/ApiGateways/OcelotApiGateway/Dockerfile

  shopping.aggregator:
    image: ${DOCKER_REGISTRY-}shoppingaggregator
    build:
      context: .
      dockerfile: src/ApiGateways/Shopping.Aggregator/Dockerfile

volumes:
  mongo_data:
  postgres_data:
  pgadmin_data :





